version: '3.8'

services:
  foreign_exchange_service:
    image: foreign_exchange_service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - h2db-data-volume:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 30s
      start_period: 30s
      retries: 3

volumes:
  h2db-data-volume:
    driver: local
